#!/bin/bash


printf "
Installing Microsoft Teams
##########################

"

cd /tmp
wget https://packages.microsoft.com/repos/ms-teams/pool/main/t/teams/teams_1.3.00.16851_amd64.deb
sudo dpkg -i teams_1.3.00.16851_amd64.deb

printf "

####################
DONE
"
