#!/bin/bash

printf "
Installing JetBrains PyCharm
############################

"
sudo apt-get install -y wget apt-transport-https
cd /tmp
wget "https://download.jetbrains.com/python/pycharm-community-2019.3.tar.gz" -O pycharm-community-2019.3.tar.gz
tar xfz pycharm-*.tar.gz -C /opt/
cd /opt/pycharm-*/bin
sudo ./pycharm.sh

printf "

####################
DONE
"

