#!/bin/bash

# chrome
printf "
Installing Google Chrome Browser
################################

"

sudo apt-get install -y wget apt-transport-https gnupg2
wget -q -O - "https://dl-ssl.google.com/linux/linux_signing_key.pub" | sudo apt-key add - 
echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee > /etc/apt/sources.list.d/google.list
sudo apt-get update
sudo apt-get install -y google-chrome-stable

printf "

####################
DONE
"

