#!/bin/bash

printf "
Installing Postman
##############################

"
sudo apt-get install -y wget apt-transport-https
cd /tmp
wget "https://dl.pstmn.io/download/latest/linux64" -O postman-linux-x64.tar.gz
tar -xvzf postman-linux-x64.tar.gz -C /opt
mkdir -p ~/.local/share/applications
touch ~/.local/share/applications/postman2.desktop

mkdir -p ~/.local/share/applications

printf '
[Desktop Entry]
Name=Postman
GenericName=API Client
X-GNOME-FullName=Postman API Client
Comment=Make and view REST API calls and responses
Keywords=api;
Exec=/opt/Postman/Postman
Terminal=false
Type=Application
Icon=/opt/Postman/app/resources/app/assets/icon.png
Categories=Development;Utilities;
' >> ~/.local/share/applications/postman2.desktop

sudo ln -s /opt/Postman/Postman /usr/bin/postman

printf "

####################
DONE
"
