#!/bin/bash

#set -e

printf "
Installing BFG Repo Cleaner
###########################

"

# install java
sudo apt-get update -qq
sudo apt-get install -yq default-jre-headless

# fetch latest bfg.jar
cd /tmp
wget -q https://repo1.maven.org/maven2/com/madgag/bfg/1.13.0/bfg-1.13.0.jar -O bfg-latest.jar
sudo cp bfg-latest.jar /usr/local/bin/bfg-latest.jar

# install to /usr/local/bin
cat << EOF > /usr/local/bin/bfg
#!/bin/bash
java -jar /usr/local/bin/bfg-latest.jar \$@
EOF

# mark executable
sudo chmod +x /usr/local/bin/bfg*

printf "

####################
DONE
"

