#!/bin/bash

printf "
Installing Sublime Text 3
#########################

"

sudo apt-get install -y wget apt-transport-https gnupg2
wget -qO - "https://download.sublimetext.com/sublimehq-pub.gpg" | sudo apt-key add -
echo "deb https://download.sublimetext.com/ apt/stable/" |\
  sudo tee /etc/apt/sources.list.d/sublime-text.list
sudo apt-get update
sudo apt-get install -y sublime-text

printf "

####################
DONE
"

