#!/bin/bash

printf "
Installing Slack
################

"

sudo apt-get install -y wget apt-transport-https
cd /tmp && wget "https://downloads.slack-edge.com/linux_releases/slack-desktop-4.4.2-amd64.deb"
sudo dpkg -i slack-desktop*.deb
sudo apt-get -f -y install

printf "

####################
DONE
"
