#!/bin/bash

printf "
Installing DBeaver
##################

"

sudo apt-get install -y openjdk-11-jre-headless \
	openjdk-11-jdk-headless \
	wget \
	apt-transport-https
cd /tmp
wget https://dbeaver.io/files/dbeaver-ce_latest_amd64.deb
sudo dpkg -i dbeaver-ce_latest_amd64.deb

printf "

####################
DONE
"
