#!/bin/bash

printf "
Installing Docker
####################

"

sudo apt-get remove -y docker docker-engine docker.io
sudo apt-get install -y \
    apt-transport-https \
    ca-certificates \
    curl \
    wget \
    software-properties-common
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo apt-key fingerprint 0EBFCD88
export VERSION_CODENAME=$(grep VERSION_CODENAME /etc/os-release | cut -d'=' -f2)
sudo add-apt-repository \
    "deb [arch=amd64] https://download.docker.com/linux/ubuntu $VERSION_CODENAME stable"
sudo apt-get install -y docker.io
sudo apt-get update
sudo apt-get install -y docker-ce
# Allow docker to work without sudo
sudo usermod -aG docker $USER
sudo newgrp docker

printf "

####################
DONE

Now log out and log back in to use Docker without sudo.
"

