#!/bin/bash

printf "
Setting time zone and locale
############################

"

export DEBIAN_FRONTEND=noninteractive
sudo apt-get update
sudo apt-get install -y --no-install-recommends tzdata locales
# Timezone / Locale stuff
sudo ln -fs /usr/share/zoneinfo/America/Chicago /etc/localtime
sudo dpkg-reconfigure --frontend noninteractive tzdata
echo "en_US.UTF-8 UTF-8" | sudo tee -a /etc/locale.gen
sudo locale-gen en_US.UTF-8
sudo update-locale LANG="en_US.UTF-8" LC_MESSAGES="POSIX"
sudo dpkg-reconfigure --frontend noninteractive locales


printf "

####################
DONE

Time zone set to Chicago, and local/lang set to en_US.UTF-8
"
