#!/bin/bash

export DEBIAN_FRONTEND=noninteractive

printf "
Updating packages...
####################

"

sudo apt-get update -qq

printf "
Upgrading packages...
#####################

"

sudo apt-get upgrade -y -qq
printf "
Cleaning up...
##############

"

sudo apt-get clean
sudo apt-get autoremove -y

printf "

####################
DONE
"


